feat: add button components
idealjs/camphora pull request #20
Opened 2023-07-31 15:44 UTC by wushide

feat: add button components

2023-08-01 02:43 UTC, cqh963852 requested changes

2023-08-01 02:43 UTC, cqh963852 commented on packages/camphora-styled/src/button.css.ts
> +export const primaryButton = style({
这里不用合并 button 的 style

用户的使用方式是 

这里的 active 属性需要补充到 buttonActive 中。

用户可能会用代码控制 active 属性。

类似用法

`<button classname={clsx(button, buttonPrimary)} />`

2023-08-01 02:43 UTC, cqh963852 commented on packages/camphora-styled/src/button.css.ts
> +export const primaryButton = style({
命名部分，组件在前，修饰在后

这里应该是`buttonPrimary`,`buttonInfo`

2023-08-01 02:43 UTC, cqh963852 commented on packages/camphora-styled/src/button.css.ts
> +export const primaryButton = style({
另外需要加上 selector，保证 buttonPrimary ，buttonInfo 等修饰在拥有 button 的情况下才生效。

`<button classname={buttonPrimary} />` 应该不生效

```
const button = style({
  [`&${buttonInfo}`]:{
    // some style override
  }
})
```

2023-08-01 02:43 UTC, cqh963852 commented on packages/camphora-styled/src/button.css.ts
> -    [`&:hover, ${buttonActive}&`]: {
这里的 `buttonActive` 是交给用户控制的，所以不应该移除。

2023-08-01 02:43 UTC, cqh963852 commented on apps/website/docs/components/Actions/button/BrandColorButtons.tsx
> +  const buttonSpacing = 8; // 设置按钮之间的垂直间距（以像素为单位）
常量应该定义在组件的外部。

2023-08-01 02:43 UTC, cqh963852 commented on apps/website/docs/components/Actions/button/BrandColorButtons.tsx
> +      <div className={clsx(button, neutralButton)} style={{ marginRight: buttonSpacing }}>
可以提取一下 style 对象。

文档部分可以粗糙一点。直接 `margin: buttonSpacing` , 简单又方便

2023-08-03 03:14 UTC, wushide commented
Issues with reviews have been modified

2023-08-03 03:25 UTC, cqh963852 requested changes

2023-08-03 03:25 UTC, cqh963852 commented on apps/website/docs/components/Actions/button/BrandColorButtons.tsx
> +export default Button;
这里末尾的 end of line 可能有点问题。可能是 windows 系统下的 crlf

2023-08-03 03:28 UTC, cqh963852 requested changes

2023-08-03 03:28 UTC, cqh963852 commented on apps/website/docs/components/Actions/button/BrandColorButtons.tsx
> +      <div className={clsx(button, buttonNeutral)} style={{ marginRight: buttonSpacing }}>
这里的 style 提取到 const 变量吧

```
const style: CSSProperties = {
  margin: buttonSpacing
}
```

2023-08-03 07:04 UTC, cqh963852 commented
补充一下 CodeBlock 用于显示组件代码。可以参考

https://github.com/idealjs/camphora/blob/9f6ec33b9501aeefe969db0b018dad0aa25028f0/apps/website/docs/components/Actions/Drawer.mdx#L17

2023-08-03 07:04 UTC, cqh963852 requested changes
补充一下 CodeBlock 用于显示组件代码。可以参考

https://github.com/idealjs/camphora/blob/9f6ec33b9501aeefe969db0b018dad0aa25028f0/apps/website/docs/components/Actions/Drawer.mdx#L17

2023-08-03 07:40 UTC, cqh963852 requested changes

2023-08-03 07:40 UTC, cqh963852 commented on apps/website/docs/components/Actions/button/BrandColorButtons.tsx
> +export default Button;
这里又出现了 CRLF，可能 git 配置有问题。

参考 https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

2023-08-03 08:50 UTC, cqh963852 approved these changes

2023-08-03 08:54 UTC, merged